# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PhilleConnect
email: it@polarwinkel.de
description: > # this means to ignore newlines until "baseurl:"
  The Free and Open Source, Modular, Docker-Based School Network Solution
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://philleconnect.org" # the base hostname & protocol for your site

include: ['_pages']
# Build settings
markdown: kramdown


# GitHub default (can be set to custom stuff)
#github: [metadata]
#encoding: UTF-8
#kramdown:
#  input: GFM
#  hard_wrap: false
#future: true
#jailed: false
#theme: jekyll-theme-primer
#gfm_quirks: paragraph_end
# GitHub default (would be overwritten by GitHub)
#lsi: false
#safe: true
#source: [your repo's top level directory]
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
